version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    volumes:
      - .:/appset
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=apptest
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    # network_mode: "host"
  db:
    image: mysql:5.7.18
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - var/lib/mysql
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
