# development:
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: root
#   password: 1234
#   database: petrastudio
#   socket: /tmp/mysql.sock
production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  port: 3306
  username: root
  password: 1234
  host: db
  database: apptest
  socket: /tmp/mysql.sock
